# kitty --start-as maximized

shell_integration       disabled
background_opacity      1.0
background_blur         0

# hide borders and title bar
hide_window_decorations yes

enable_audio_bell       no

# colors
wayland_titlebar_color  system
macos_titlebar_color    system

# clipboard
clipboard_control write-clipboard write-primary read-clipboard read-primary

include fonts/jetbrains-mono.conf
include themes/catppuccin-mocha.conf
