protocol file
fragment_matches [0-9]+
action launch --type=tab --cwd=current /usr/local/bin/hx +${FRAGMENT} -- ${FILE_PATH}

protocol file
mime text/*
action launch --type=tab --cwd=current /usr/local/bin/hx -- ${FILE_PATH}
