window:

  opacity: 1.0


font:

  normal:
    family: FiraCode Nerd Font
    style: Regular

  bold:
    family: FiraCode Nerd Font
    style: Medium

  italic:
    family: FiraCode Nerd Font
    style: Regular

  bold_italic:
    family: FiraCode Nerd Font
    style: Medium

  size: 20.0


colors:

  primary:
    background: '#1E1E1E'
    foreground: '#E0E0E0'

  cursor:
    text: CellBackground
    cursor: CellForeground

  normal:
    black:   '#1E1E1E'
    red:     '#E33A3A'
    green:   '#37BA70'
    yellow:  '#E7C930'
    blue:    '#3882CC'
    magenta: '#9446E3'
    cyan:    '#51B4CC'
    white:   '#D1D1D1'

  bright:
    black:   '#383838'
    red:     '#F94040'
    green:   '#3DCC7B'
    yellow:  '#FDDC35'
    blue:    '#3B8FED'
    magenta: '#A34DF9'
    cyan:    '#59C5E0'
    white:   '#F4F4F4'

  transparent_background_colors: false


live_config_reload: false
