## prefix
set -g prefix C-a
bind C-a send-prefix
unbind C-b

## config
setw -g mouse on
set -g base-index 1
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm*:Tc:sitm=\E[3m'

## plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @tilish-default 'tiled'
set -g @plugin 'jabirali/tmux-tilish'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone --depth=1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run -b '~/.tmux/plugins/tpm/tpm'

set -g @override_copy_command 'clipcopy'

## binds
#bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection
bind e run-shell "tmux setw synchronize-panes \
                  $(tmux show-options -w | grep -q 'synchronize-panes on' \
                    && echo off || echo on)"
bind c clear-history
bind x kill-pane

set -g history-limit 131072

# solarized-osaka theme: github:craftzdog/solarized-osaka.nvim/extras/tmux/solarized_osaka_dark.tmux

set -g mode-style "fg=#268bd3,bg=#063540"

set -g message-style "fg=#268bd3,bg=#063540"
set -g message-command-style "fg=#268bd3,bg=#063540"

set -g pane-border-style "fg=#063540"
set -g pane-active-border-style "fg=#268bd3"

set -g status "on"
set -g status-justify "left"

set -g status-style "fg=#268bd3,bg=#002c38"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g @status_norm "#[fg=#001014,bg=#268bd3]"
set -g @status_sync "#[fg=#001014,bg=#d23681]"
set -g @status_norm_after "#[fg=#268bd3,bg=#002c38,nobold]"
set -g @status_sync_after "#[fg=#d23681,bg=#002c38,nobold]"
set -g @status_rst "#[nounderscore,noitalics]"
set -g status-left "#{?pane_synchronized,\
#[bold]#{@status_sync} #S #{@status_sync_after}#{@status_norm}#{@status_rst},\
#[bold]#{@status_norm} #S #{@status_norm_after}#{@status_norm}#{@status_rst}}"

set -g status-right "#[fg=#002c38,bg=#002c38,nobold,nounderscore,noitalics]#[fg=#268bd3,bg=#002c38] #{prefix_highlight} #[fg=#063540,bg=#002c38,nobold,nounderscore,noitalics]#[fg=#268bd3,bg=#063540] %Y-%m-%d  %I:%M %p #[fg=#268bd3,bg=#063540,nobold,nounderscore,noitalics]#[fg=#001014,bg=#268bd3,bold] #h "
if-shell '[ "$(tmux show-option -gqv "clock-mode-style")" == "24" ]' {
  set -g status-right "#[fg=#002c38,bg=#002c38,nobold,nounderscore,noitalics]#[fg=#268bd3,bg=#002c38] #{prefix_highlight} #[fg=#063540,bg=#002c38,nobold,nounderscore,noitalics]#[fg=#268bd3,bg=#063540] %Y-%m-%d  %H:%M #[fg=#268bd3,bg=#063540,nobold,nounderscore,noitalics]#[fg=#001014,bg=#268bd3,bold] #h "
}

setw -g window-status-activity-style "underscore,fg=#9eabac,bg=#002c38"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#9eabac,bg=#002c38"
setw -g window-status-format "#[fg=#002c38,bg=#002c38,nobold,nounderscore,noitalics]#[default] #I  #W #F #[fg=#002c38,bg=#002c38,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=#002c38,bg=#063540,nobold,nounderscore,noitalics]#[fg=#268bd3,bg=#063540,bold] #I  #W #F #[fg=#063540,bg=#002c38,nobold,nounderscore,noitalics]"

# tmux-plugins/tmux-prefix-highlight support
set -g @prefix_highlight_output_prefix "#[fg=#b28500]#[bg=#002c38]#[fg=#002c38]#[bg=#b28500]"
set -g @prefix_highlight_output_suffix ""
