git:
  autoFetch: false
  disableAutoEditor: false
  pagers:
    - pager: delta --dark --paging=never --color-only --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}";

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#666666'
      - bold
    inactiveBorderColor:
      - '#3a3a3a'
    searchingActiveBorderColor:
      - '#aa6666'
    selectedLineBgColor:
      - '#3a3a3a'
    inactiveViewSelectedLineBgColor:
      - '#2a2a2a'
