# Lackluster theme for kitty

foreground #CCCCCC
background #101010

# Selection highlight
selection_foreground #000000
selection_background #CCCCCC

# The color for highlighting URLs on mouse-over
url_color #D7007D

# Cursor
cursor #CCCCCC
cursor_text_color #000000

color0 #080808
color8 #444444

color1 #D70000
color9 #D70000

color2 #789978
color10 #789978

color3 #ffAA88
color11 #ffAA88

color4 #7788AA
color12 #7788AA

color5 #AA6666
color13 #AA6666

# Cyan is set to lack
color6 #708090
color14 #708090

# White is set to luster
color7 #DEEEED
color15 #DEEEED
