(custom-set-variables
 '(auto-save-default nil)
 '(auto-save-list-file-prefix nil)
 '(column-number-mode t)
 '(company-minimum-prefix-length 2)
 '(delete-selection-mode nil)
 '(display-line-numbers-type 'relative)
 '(eglot-autoshutdown t)
 '(eglot-ignored-server-capabilities '(:inlayHintProvider))
 '(global-display-line-numbers-mode t)
 '(global-git-gutter-mode t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(make-backup-files nil)
 '(menu-bar-mode nil)
 '(pop-up-windows t)
 '(scroll-margin 2)
 '(switch-to-buffer-in-dedicated-window 'pop)
 '(tab-width 4)
 '(tool-bar-mode nil))
(custom-set-faces
 )
